// Generated by https://quicktype.io

export interface Country {
  alpha2code:        string;
  alpha3code:        string;
  alt_spellings:     string[];
  area:              number;
  borders:           string[];
  calling_codes:     string[];
  capital:           string;
  currencies:        Currency[];
  demonym:           string;
  flag:              string;
  gini:              number;
  languages:         Language[];
  latitude:          number;
  longitude:         number;
  name:              string;
  native_name:       string;
  numeric_code:      string;
  population:        number;
  region:            string;
  regional_blocs:    RegionalBloc[];
  subregion:         string;
  timezones:         string[];
  top_level_domains: string[];
}

export interface Currency {
  code:   string;
  name:   string;
  symbol: string;
}

export interface Language {
  iso639_1:    string;
  iso639_2:    string;
  name:        string;
  native_name: string;
}

export interface RegionalBloc {
  acronym: string;
  name:    string;
}
